name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate GitHub Contribution Game
        uses: Platane/snk@master
        with:
          github_user_name: diyarguzelses
          outputs: |
            dist/space-invaders.svg
