name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: diyarguzelses
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the generated snake.svg to the output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
